name: Neon Database Branching
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  manage_db_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Neon Branch
        if: github.event.action != 'closed'
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
          branch_name: preview/pr-${{ github.event.number }}
          parent_branch: main

      - name: Delete Neon Branch
        if: github.event.action == 'closed'
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
          branch_name: preview/pr-${{ github.event.number }}
